CREATE DATABASE miniEbay;
USE miniEbay;

CREATE TABLE accounts(
  name VARCHAR(16) PRIMARY KEY,
  pass VARCHAR(64) NOT NULL,
  salt VARCHAR(64) NOT NULL
);

CREATE TABLE auctions(
  auctionId INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(250),
  category VARCHAR(32) NOT NULL,
  buyout DECIMAL(11, 2) DEFAULT 0.00,
  status VARCHAR(7) DEFAULT 'PENDING',
  startTime DATETIME NOT NULL,
  endTime DATETIME NOT NULL
);

CREATE TABLE bids(
  bidId INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
  price DECIMAL(11, 2) NOT NULL,
  bidTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE placedBy(
  bidId INTEGER PRIMARY KEY,
  name VARCHAR(16) NOT NULL
);

CREATE TABLE bidFor(
  bidId INTEGER PRIMARY KEY,
  auctionId INTEGER NOT NULL
);